"""RDS ETL-Hub `client_setting` schema 權限階層 12 表冪等建置(v1.6.1 task-001)。

權限設定的唯一真身在目標 RDS(`AWS_RDS_TARGET_DB`),供多台機器直讀;本應用只是維護
入口。建置方式比照 `app.etl.semantic_schema` 前例:`CREATE SCHEMA IF NOT EXISTS` +
逐表 `CREATE TABLE IF NOT EXISTS` + `CREATE INDEX IF NOT EXISTS`,可重複執行不報錯、
不刪除任何既有結構(**無任何 DROP**)。

**注意**:此 DDL 位於目標 RDS,不走 alembic(alembic 只管本專案自有 DB);識別字全為
白名單常值(schema / table / column / constraint 名皆固定字面量),不接受任何使用者
輸入,對齊 `docs/Design-Base/04-databases/04-sql-safety.md`。`COMMENT ON` 不支援
bind 參數,註解文字同為常值。

時間欄位:一律 naive `timestamp` 存 UTC+8(`04-databases/06-timezone.md`),禁
timestamptz;RDS 系統時鐘為 UTC,故 DEFAULT 需 `now() AT TIME ZONE 'Asia/Taipei'`
轉出本地 naive 值。

跨庫關聯:`client_roles` / `client_exception_sets` 以 `api_client_uid`(UUID)冷關聯
自有 DB 的 API Client 本體,**不建跨庫 FK**。
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection, AsyncEngine, create_async_engine
from sqlalchemy.pool import NullPool

from app.etl.reader import rds_database_url
from app.etl.writer import RDS_TARGET_DB_ENV
from app.models.client_setting import (
    CLIENT_SETTING_SCHEMA,
    CLIENT_SETTING_TABLES,
    ZERO_UUID,
)

_NOW_TW = "(now() AT TIME ZONE 'Asia/Taipei')"


def _create_table_sql(table: str, uid_column: str, business_columns: str) -> str:
    """組出單表 `CREATE TABLE IF NOT EXISTS`(BaseModel 共通欄位由本函式統一補齊)。"""
    return f"""
    CREATE TABLE IF NOT EXISTS {CLIENT_SETTING_SCHEMA}.{table} (
        pid bigint GENERATED BY DEFAULT AS IDENTITY
            CONSTRAINT pk_{table} PRIMARY KEY,
        {uid_column} uuid NOT NULL DEFAULT gen_random_uuid()
            CONSTRAINT uq_{table}_{uid_column} UNIQUE,
{business_columns}
        is_deleted boolean NOT NULL DEFAULT false,
        created_at timestamp NOT NULL DEFAULT {_NOW_TW},
        updated_at timestamp NOT NULL DEFAULT {_NOW_TW},
        created_by uuid NOT NULL DEFAULT '{ZERO_UUID}',
        updated_by uuid NOT NULL DEFAULT '{ZERO_UUID}'
    )
    """


# 各表業務欄位(BaseModel 共通欄位不列於此,由 _create_table_sql 補);
# 順序即 FK 依賴順序,建表須照此序
_TABLE_DDL: tuple[tuple[str, str, str], ...] = (
    (
        "services",
        "service_uid",
        """        code varchar(50) NOT NULL,
        name varchar(100) NOT NULL,
        description text,""",
    ),
    (
        "operations",
        "operation_uid",
        f"""        service_pid bigint NOT NULL
            CONSTRAINT fk_operations_service
            REFERENCES {CLIENT_SETTING_SCHEMA}.services (pid),
        name varchar(100) NOT NULL,
        description text,""",
    ),
    (
        "operation_items",
        "operation_item_uid",
        f"""        operation_pid bigint NOT NULL
            CONSTRAINT fk_operation_items_operation
            REFERENCES {CLIENT_SETTING_SCHEMA}.operations (pid),
        table_name varchar(200) NOT NULL,
        column_name varchar(200) NOT NULL,""",
    ),
    (
        "permission_profiles",
        "permission_profile_uid",
        """        name varchar(100) NOT NULL,
        description text,""",
    ),
    (
        "profile_operations",
        "profile_operation_uid",
        f"""        permission_profile_pid bigint NOT NULL
            CONSTRAINT fk_profile_operations_permission_profile
            REFERENCES {CLIENT_SETTING_SCHEMA}.permission_profiles (pid),
        operation_pid bigint NOT NULL
            CONSTRAINT fk_profile_operations_operation
            REFERENCES {CLIENT_SETTING_SCHEMA}.operations (pid),""",
    ),
    (
        "profile_items",
        "profile_item_uid",
        f"""        permission_profile_pid bigint NOT NULL
            CONSTRAINT fk_profile_items_permission_profile
            REFERENCES {CLIENT_SETTING_SCHEMA}.permission_profiles (pid),
        operation_pid bigint NOT NULL
            CONSTRAINT fk_profile_items_operation
            REFERENCES {CLIENT_SETTING_SCHEMA}.operations (pid),
        table_name varchar(200) NOT NULL,
        column_name varchar(200) NOT NULL,
        action varchar(10) NOT NULL
            CONSTRAINT ck_profile_items_action CHECK (action IN ('read', 'edit')),""",
    ),
    (
        "roles",
        "role_uid",
        f"""        permission_profile_pid bigint NOT NULL
            CONSTRAINT fk_roles_permission_profile
            REFERENCES {CLIENT_SETTING_SCHEMA}.permission_profiles (pid),
        name varchar(100) NOT NULL,
        description text,""",
    ),
    (
        "client_roles",
        "client_role_uid",
        f"""        api_client_uid uuid NOT NULL,
        role_pid bigint NOT NULL
            CONSTRAINT fk_client_roles_role
            REFERENCES {CLIENT_SETTING_SCHEMA}.roles (pid),""",
    ),
    (
        "exception_sets",
        "exception_set_uid",
        """        name varchar(100) NOT NULL,
        description text,""",
    ),
    (
        "exception_operations",
        "exception_operation_uid",
        f"""        exception_set_pid bigint NOT NULL
            CONSTRAINT fk_exception_operations_exception_set
            REFERENCES {CLIENT_SETTING_SCHEMA}.exception_sets (pid),
        operation_pid bigint NOT NULL
            CONSTRAINT fk_exception_operations_operation
            REFERENCES {CLIENT_SETTING_SCHEMA}.operations (pid),""",
    ),
    (
        "exception_items",
        "exception_item_uid",
        f"""        exception_set_pid bigint NOT NULL
            CONSTRAINT fk_exception_items_exception_set
            REFERENCES {CLIENT_SETTING_SCHEMA}.exception_sets (pid),
        operation_pid bigint NOT NULL
            CONSTRAINT fk_exception_items_operation
            REFERENCES {CLIENT_SETTING_SCHEMA}.operations (pid),
        table_name varchar(200) NOT NULL,
        column_name varchar(200) NOT NULL,
        action varchar(10) NOT NULL
            CONSTRAINT ck_exception_items_action CHECK (action IN ('read', 'edit')),""",
    ),
    (
        "client_exception_sets",
        "client_exception_set_uid",
        f"""        api_client_uid uuid NOT NULL,
        exception_set_pid bigint NOT NULL
            CONSTRAINT fk_client_exception_sets_exception_set
            REFERENCES {CLIENT_SETTING_SCHEMA}.exception_sets (pid),
        expires_at timestamp,""",
    ),
)

# FK 欄位索引(`09-indexes-and-perf.md`:外鍵欄位必索引)
_FK_INDEX_DDL: tuple[tuple[str, str, str], ...] = (
    ("idx_operations_service_pid", "operations", "service_pid"),
    ("idx_operation_items_operation_pid", "operation_items", "operation_pid"),
    (
        "idx_profile_operations_permission_profile_pid",
        "profile_operations",
        "permission_profile_pid",
    ),
    ("idx_profile_operations_operation_pid", "profile_operations", "operation_pid"),
    ("idx_profile_items_permission_profile_pid", "profile_items", "permission_profile_pid"),
    ("idx_profile_items_operation_pid", "profile_items", "operation_pid"),
    ("idx_roles_permission_profile_pid", "roles", "permission_profile_pid"),
    ("idx_client_roles_role_pid", "client_roles", "role_pid"),
    (
        "idx_exception_operations_exception_set_pid",
        "exception_operations",
        "exception_set_pid",
    ),
    ("idx_exception_operations_operation_pid", "exception_operations", "operation_pid"),
    ("idx_exception_items_exception_set_pid", "exception_items", "exception_set_pid"),
    ("idx_exception_items_operation_pid", "exception_items", "operation_pid"),
    (
        "idx_client_exception_sets_exception_set_pid",
        "client_exception_sets",
        "exception_set_pid",
    ),
)

# 業務唯一鍵:一律 partial unique(軟刪除後允許以同名 / 同組合重建,對齊既有 api_client_users)
_UNIQUE_INDEX_DDL: tuple[tuple[str, str, str], ...] = (
    ("uq_services_code", "services", "code"),
    ("uq_operations_service_pid_name", "operations", "service_pid, name"),
    (
        "uq_operation_items_operation_table_column",
        "operation_items",
        "operation_pid, table_name, column_name",
    ),
    ("uq_permission_profiles_name", "permission_profiles", "name"),
    (
        "uq_profile_operations_profile_operation",
        "profile_operations",
        "permission_profile_pid, operation_pid",
    ),
    (
        "uq_profile_items_profile_operation_table_column_action",
        "profile_items",
        "permission_profile_pid, operation_pid, table_name, column_name, action",
    ),
    ("uq_roles_name", "roles", "name"),
    # API Client 只綁 0..1 Role:未刪列以 api_client_uid 唯一保證
    ("uq_client_roles_api_client_uid", "client_roles", "api_client_uid"),
    ("uq_exception_sets_name", "exception_sets", "name"),
    (
        "uq_exception_operations_set_operation",
        "exception_operations",
        "exception_set_pid, operation_pid",
    ),
    (
        "uq_exception_items_set_operation_table_column_action",
        "exception_items",
        "exception_set_pid, operation_pid, table_name, column_name, action",
    ),
    (
        "uq_client_exception_sets_client_exception_set",
        "client_exception_sets",
        "api_client_uid, exception_set_pid",
    ),
)

_TABLE_COMMENTS: dict[str, str] = {
    "services": "系統別:作業的分類容器 / Service: category container of operations",
    "operations": "作業:查詢入口,歸屬一個系統別 / Operation: query entry under a service",
    "operation_items": "作業範圍:表 × 欄位 / Operation scope: table x column",
    "permission_profiles": "角色權限設定檔 / Permission profile",
    "profile_operations": "設定檔勾選的可讀作業 / Operations granted by a profile",
    "profile_items": "設定檔權限項:作業 × 表 × 欄位 × 動作 / Profile permission items",
    "roles": "Role:必綁 1 個設定檔 / Role: bound to exactly one profile",
    "client_roles": "API Client 的 Role 指派(0..1)/ API client role assignment (0..1)",
    "exception_sets": "特例權限組(可重用)/ Reusable exception permission set",
    "exception_operations": "特例組勾選的作業 / Operations granted by an exception set",
    "exception_items": "特例組權限項 / Exception set permission items",
    "client_exception_sets": (
        "API Client 的特例組綁定(可設效期)/ Client exception set binding (with expiry)"
    ),
}

_BASE_COLUMN_COMMENTS: dict[str, str] = {
    "pid": "內部主鍵(禁對外暴露)/ Internal primary key (never exposed)",
    "is_deleted": "軟刪除旗標 / Soft delete flag",
    "created_at": "建立時間(UTC+8)/ Created at (UTC+8)",
    "updated_at": "更新時間(UTC+8)/ Updated at (UTC+8)",
    "created_by": "建立者 / Created by",
    "updated_by": "最後更新者 / Updated by",
}

_UID_COMMENT = "對外識別碼 / External identifier"

_NAME_COMMENT = "名稱 / Name"
_DESCRIPTION_COMMENT = "說明 / Description"
_TABLE_NAME_COMMENT = "資料表(語意層英文名)/ Table (semantic English name)"
_COLUMN_NAME_COMMENT = "欄位(* 代表全欄位)/ Column (* means all columns)"
_ACTION_COMMENT = "動作 read / edit(edit 含新增 · 更新 · 刪除)/ Action read or edit"
_API_CLIENT_UID_COMMENT = (
    "API Client 對外識別碼(跨庫冷關聯,本體在自有 DB,無 FK)"
    "/ API client UID (cross-database soft reference, no FK)"
)
_OPERATION_PID_COMMENT = "歸屬作業 / Owning operation"

_BUSINESS_COLUMN_COMMENTS: dict[str, dict[str, str]] = {
    "services": {
        "code": "系統別代碼 erp / crm / hrm… / Service code",
        "name": _NAME_COMMENT,
        "description": _DESCRIPTION_COMMENT,
    },
    "operations": {
        "service_pid": "歸屬系統別 / Owning service",
        "name": "作業名(系統別內唯一)/ Operation name (unique within service)",
        "description": _DESCRIPTION_COMMENT,
    },
    "operation_items": {
        "operation_pid": _OPERATION_PID_COMMENT,
        "table_name": _TABLE_NAME_COMMENT,
        "column_name": _COLUMN_NAME_COMMENT,
    },
    "permission_profiles": {
        "name": "設定檔名(唯一)/ Profile name (unique)",
        "description": _DESCRIPTION_COMMENT,
    },
    "profile_operations": {
        "permission_profile_pid": "歸屬設定檔 / Owning profile",
        "operation_pid": "勾選的作業 / Granted operation",
    },
    "profile_items": {
        "permission_profile_pid": "歸屬設定檔 / Owning profile",
        "operation_pid": "歸屬作業(授權巢狀在作業下)/ Owning operation",
        "table_name": _TABLE_NAME_COMMENT,
        "column_name": _COLUMN_NAME_COMMENT,
        "action": _ACTION_COMMENT,
    },
    "roles": {
        "permission_profile_pid": "綁定的設定檔(必綁)/ Bound profile (mandatory)",
        "name": "角色名(唯一)/ Role name (unique)",
        "description": _DESCRIPTION_COMMENT,
    },
    "client_roles": {
        "api_client_uid": _API_CLIENT_UID_COMMENT,
        "role_pid": "指派的 Role / Assigned role",
    },
    "exception_sets": {
        "name": "特例權限名(唯一)/ Exception set name (unique)",
        "description": _DESCRIPTION_COMMENT,
    },
    "exception_operations": {
        "exception_set_pid": "歸屬特例組 / Owning exception set",
        "operation_pid": "勾選的作業 / Granted operation",
    },
    "exception_items": {
        "exception_set_pid": "歸屬特例組 / Owning exception set",
        "operation_pid": _OPERATION_PID_COMMENT,
        "table_name": _TABLE_NAME_COMMENT,
        "column_name": _COLUMN_NAME_COMMENT,
        "action": _ACTION_COMMENT,
    },
    "client_exception_sets": {
        "api_client_uid": _API_CLIENT_UID_COMMENT,
        "exception_set_pid": "綁定的特例組 / Bound exception set",
        "expires_at": "效期(UTC+8;NULL 代表不設限)/ Expires at (UTC+8; NULL means never)",
    },
}


def _comment_statements() -> list[str]:
    """組出全部 `COMMENT ON`(冪等:重下即覆寫同值)。"""
    statements: list[str] = []
    for table, uid_column, _ in _TABLE_DDL:
        qualified = f"{CLIENT_SETTING_SCHEMA}.{table}"
        statements.append(f"COMMENT ON TABLE {qualified} IS '{_TABLE_COMMENTS[table]}'")
        statements.append(f"COMMENT ON COLUMN {qualified}.{uid_column} IS '{_UID_COMMENT}'")
        for column, comment in _BUSINESS_COLUMN_COMMENTS[table].items():
            statements.append(f"COMMENT ON COLUMN {qualified}.{column} IS '{comment}'")
        for column, comment in _BASE_COLUMN_COMMENTS.items():
            statements.append(f"COMMENT ON COLUMN {qualified}.{column} IS '{comment}'")
    return statements


async def ensure_client_setting_schema(conn: AsyncConnection) -> None:
    """冪等建置 `client_setting` schema 與 12 張權限表(存在則略過,不刪除既有結構)。"""
    await conn.execute(text(f"CREATE SCHEMA IF NOT EXISTS {CLIENT_SETTING_SCHEMA}"))
    for table, uid_column, business_columns in _TABLE_DDL:
        await conn.execute(text(_create_table_sql(table, uid_column, business_columns)))
    for index_name, table, column in _FK_INDEX_DDL:
        await conn.execute(
            text(
                f"CREATE INDEX IF NOT EXISTS {index_name}"
                f" ON {CLIENT_SETTING_SCHEMA}.{table} ({column})"
            )
        )
    for index_name, table, columns in _UNIQUE_INDEX_DDL:
        await conn.execute(
            text(
                f"CREATE UNIQUE INDEX IF NOT EXISTS {index_name}"
                f" ON {CLIENT_SETTING_SCHEMA}.{table} ({columns})"
                " WHERE is_deleted = false"
            )
        )
    for statement in _comment_statements():
        await conn.execute(text(statement))


@asynccontextmanager
async def client_setting_engine() -> AsyncIterator[AsyncEngine]:
    """指向目標 RDS(權限設定真身)的 engine;離開 context 即釋放連線。"""
    engine = create_async_engine(rds_database_url(RDS_TARGET_DB_ENV), poolclass=NullPool)
    try:
        yield engine
    finally:
        await engine.dispose()


async def ensure_client_setting_schema_on_target() -> None:
    """自建連線對目標 RDS 執行冪等建置(供啟動 / 維運腳本呼叫)。"""
    async with client_setting_engine() as engine, engine.begin() as conn:
        await ensure_client_setting_schema(conn)


__all__ = [
    "CLIENT_SETTING_SCHEMA",
    "CLIENT_SETTING_TABLES",
    "client_setting_engine",
    "ensure_client_setting_schema",
    "ensure_client_setting_schema_on_target",
]
